name: deploy-to-production

on:
  workflow_dispatch:  # Allow manual triggering from the GitHub UI


jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Deploy to PROD
      run: |
        echo "Deploying to PROD env"
  