name: deploy-to-production

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to trigger'
        required: true
        default: 'main'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
      # Ensure the workflow only runs on the main branch
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Deploy to PROD
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to PROD env"
