name: deploy-to-production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
      # Ensure the workflow only runs on the main branch
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Deploy to PROD
      run: |
        echo "Deploying to PROD env"